---
language: rust
sudo: false

matrix:
  include:
    # Minimum rustc version
    - rust: 1.20.0
      # - rust: nightly

script:
  - RUST_TEST_THREADS=1 RUST_LOG="futures_pool=trace" cargo test --test pool natural_shutdown_simple_futures -- --nocapture
  # - cargo test
    # - 'if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo test --benches; fi'
  - # - rustdoc --test README.md -L target/debug/deps
  - # - cargo doc --no-deps

notifications:
  email:
    on_success: never
