---
language: rust
sudo: false

matrix:
  include:
    # Minimum rustc version
    - rust: 1.20.0
    - rust: nightly

script:
  - cargo test
  - 'if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo test --benches; fi'
  - rustdoc --test README.md -L target/debug/deps
  - cargo doc --no-deps

notifications:
  email:
    on_success: never
